[package]
name = "vaultrs-login"
version = "0.1.4"
authors = ["Joshua Gilman <joshuagilman@gmail.com>"]
description = "Adds login support for Vault clients from vaultrs."
license = "MIT"
readme = "README.md"
repository = "https://github.com/jmgilman/vaultrs"
keywords = ["Vault", "API", "Client", "Hashicorp", "Login"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
aws = [
    "aws-sdk-iam",
    "aws-sdk-sts",
    "aws-sigv4",
    "aws-types",
    "base64",
    "http",
    "serde_json"
]
oidc = ["tiny_http", "tokio"]

[dependencies]
async-trait = "0.1.51"
aws-sdk-iam = { version = "0.2.0", optional = true }
aws-sdk-sts = { version = "0.2.0", optional = true }
aws-sigv4 = { version = "0.2.0", optional = true }
aws-types = { version = "0.2.0", optional = true }
base64 = { version = "0.13", optional = true }
http = { version = "0.2.4", optional = true }
serde = "1.0.130"
serde_json = { version = "1.0.66", optional = true }
tiny_http = { version = "0.8.2", optional = true }
tokio = { version = "1.11.0", optional = true }
tracing = "0.1"
url = "2.2.2"
vaultrs = { version = "0.5.4", path = ".." }

[dev-dependencies]
reqwest = "0.11.4"
tokio-test = "0.4.2"
tracing-test = "0.1"
dockertest-server = { version = "0.1.4", features = ["hashi", "auth", "cloud"] }
